[package]
name = "one-team-pad-cipher-cracker"
version = "0.1.0"
authors = ["Evan Richter <evanjrichter@gmail.com>"]
edition = "2018"

[profile.test]
opt-level = 3

[dependencies]
anyhow = "1.0"
strsim = "0.10"
linreg = "0.2"
crossbeam-channel = "0.5"
num_cpus = "1.13"
ctrlc = "3.1"
