on: [push]

name: Code Coverage

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zinstrument-coverage'
      - uses: actions-rs/install@v0.1
        with:
          crate: grcov
          version: latest
          use-tool-cache: true
      - name: generate-report
        run: grcov . -s . -t html --binary-path ./target/debug/ -o ./coverage-report/
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./coverage-report/
